### ISSUE TITLE
Use newer version of lodash

### ISSUE THREAD

**Issue by kounelios13** [d5/deep-defaults#4]
Hello.I am using `nightmare` for testing.However npm shows a security warning for the version of lodash used in `deep-defaults`.Here is the warning:
![npm](https://user-images.githubusercontent.com/11466138/44953733-3f039580-aea0-11e8-8ee0-aad9a9917661.png)

The version of `lodash` used in here is prone to Prototype pollution

And here is the link: https://nodesecurity.io/advisories/577 

Also I see that there are 2 pull requests active that fix this issue but none of them has been merged

**Comment by wojtekmaj** [comment]
Should be closed via #3 :)
